#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed

if [ -z "$1" ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ping -c 5 "$1"
